import Image from "next/image";

import type { ImageJobResponse } from "@/lib/api/imageJobs";
import { getImageResultUrl } from "@/lib/api/imageJobs";

import styles from "./studio.module.css";

export function DemoResultPreview({ job, compact = false }: Readonly<{
  job: ImageJobResponse;
  compact?: boolean;
}>) {
  const url = getImageResultUrl(job);
  if (!job.result || !url) return null;
  const demo = job.settings.provider === "demo";

  return (
    <figure className={compact ? styles.compactResult : styles.resultPreview}>
      <div className={styles.resultImageFrame}>
        <Image
          src={url}
          alt={`${demo ? "Deterministic demo" : "ComfyUI"} result for ${job.prompt}`}
          fill
          sizes={compact ? "280px" : "(max-width: 700px) 90vw, 60vw"}
          loading="eager"
          priority={!compact}
          unoptimized
        />
        <span className={styles.demoBadge}>{demo ? "Demo result" : "Live result"}</span>
      </div>
      {!compact ? (
        <figcaption>
          {demo ? "Generated by the deterministic demo renderer." : "Generated by local ComfyUI."}
        </figcaption>
      ) : null}
    </figure>
  );
}
