/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/connections/codex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Connection Status */
        get: operations["get_connection_status_api_v1_connections_codex_get"];
        put?: never;
        post?: never;
        /** Disconnect Connection */
        delete: operations["disconnect_connection_api_v1_connections_codex_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/codex/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check Connection */
        post: operations["check_connection_api_v1_connections_codex_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/codex/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Connection */
        post: operations["import_connection_api_v1_connections_codex_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connections/codex/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restart Connection */
        post: operations["restart_connection_api_v1_connections_codex_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gpt-image-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Gpt Image Job */
        post: operations["create_gpt_image_job_api_v1_gpt_image_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-edit-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Image Edit Job */
        post: operations["create_image_edit_job_api_v1_image_edit_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Image Jobs */
        get: operations["list_image_jobs_api_v1_image_jobs_get"];
        put?: never;
        /** Create Image Job */
        post: operations["create_image_job_api_v1_image_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/assets/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Image Job Assets */
        post: operations["delete_image_job_assets_api_v1_image_jobs_assets_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Image Job Tags */
        get: operations["list_image_job_tags_api_v1_image_jobs_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Job */
        get: operations["get_image_job_api_v1_image_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Image Job */
        delete: operations["cancel_image_job_api_v1_image_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/asset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Image Job Asset */
        delete: operations["delete_image_job_asset_api_v1_image_jobs__job_id__asset_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/assets/{ordinal}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Job Asset Result */
        get: operations["get_image_job_asset_result_api_v1_image_jobs__job_id__assets__ordinal__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/assets/{ordinal}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Job Asset Thumbnail */
        get: operations["get_image_job_asset_thumbnail_api_v1_image_jobs__job_id__assets__ordinal__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Image Job */
        get: operations["stream_image_job_api_v1_image_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/inputs/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Job Input */
        get: operations["get_image_job_input_api_v1_image_jobs__job_id__inputs__role__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/inputs/{role}/{ordinal}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Job Input Ordinal */
        get: operations["get_image_job_input_ordinal_api_v1_image_jobs__job_id__inputs__role___ordinal__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Job Result */
        get: operations["get_image_job_result_api_v1_image_jobs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Image Job */
        post: operations["retry_image_job_api_v1_image_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Image Job Tags */
        patch: operations["update_image_job_tags_api_v1_image_jobs__job_id__tags_patch"];
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Job Thumbnail */
        get: operations["get_image_job_thumbnail_api_v1_image_jobs__job_id__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Provider */
        get: operations["get_image_provider_api_v1_providers_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/image-edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Edit Provider */
        get: operations["get_image_edit_provider_api_v1_providers_image_edit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/image-edit/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Edit Options */
        get: operations["get_image_edit_options_api_v1_providers_image_edit_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/image/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Generation Options */
        get: operations["get_image_generation_options_api_v1_providers_image_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AspectRatio: "1:1" | "4:3" | "3:4" | "16:9";
        /** Body_create_gpt_image_job_api_v1_gpt_image_jobs_post */
        Body_create_gpt_image_job_api_v1_gpt_image_jobs_post: {
            aspectRatio: components["schemas"]["AspectRatio"];
            /**
             * Count
             * @default 1
             */
            count: number;
            /**
             * Mode
             * @default generate
             * @enum {string}
             */
            mode: "generate" | "edit";
            /**
             * Moderation
             * @default auto
             * @enum {string}
             */
            moderation: "auto" | "low";
            /** Prompt */
            prompt: string;
            /**
             * Quality
             * @default auto
             * @enum {string}
             */
            quality: "auto" | "low" | "medium" | "high";
            /**
             * Reasoningeffort
             * @default none
             * @enum {string}
             */
            reasoningEffort: "none" | "low" | "medium" | "high";
            /** References */
            references?: string[] | null;
            /** Seed */
            seed?: number | null;
            /**
             * Size
             * @default 1024x1024
             * @enum {string}
             */
            size: "1024x1024" | "1024x1536" | "1536x1024";
            style: components["schemas"]["ImageStyle"];
            /**
             * Websearch
             * @default false
             */
            webSearch: boolean;
        };
        /** Body_create_image_edit_job_api_v1_image_edit_jobs_post */
        Body_create_image_edit_job_api_v1_image_edit_jobs_post: {
            aspectRatio: components["schemas"]["AspectRatio"];
            /**
             * Cfg
             * @default 1
             */
            cfg: number;
            /** Facereference */
            faceReference?: string | null;
            /** @default fit */
            fitMode: components["schemas"]["EditFitMode"];
            /**
             * Groundingresolution
             * @default 768
             */
            groundingResolution: number;
            /**
             * Loras
             * @default []
             */
            loras: string;
            /** Prompt */
            prompt: string;
            /**
             * Referenceinfluence
             * @default 4
             */
            referenceInfluence: number;
            /**
             * Sampler
             * @default euler
             */
            sampler: string;
            /**
             * Scheduler
             * @default simple
             */
            scheduler: string;
            /** Seed */
            seed?: number | null;
            /** Source */
            source?: string | null;
            /** Sourcejobid */
            sourceJobId?: string | null;
            /**
             * Steps
             * @default 8
             */
            steps: number;
            style: components["schemas"]["ImageStyle"];
        };
        /** CodexConnectionResponse */
        CodexConnectionResponse: {
            /** Connected */
            connected: boolean;
            /** Message */
            message: string;
            /**
             * State
             * @enum {string}
             */
            state: "disconnected" | "auth_missing" | "starting" | "connected" | "reauth_required" | "proxy_error";
        };
        /** @enum {string} */
        EditFitMode: "fit" | "crop";
        /** GPTImageSettingsResponse */
        GPTImageSettingsResponse: {
            /** Count */
            count: number;
            /**
             * Moderation
             * @enum {string}
             */
            moderation: "auto" | "low";
            /**
             * Quality
             * @enum {string}
             */
            quality: "auto" | "low" | "medium" | "high";
            /**
             * Reasoningeffort
             * @enum {string}
             */
            reasoningEffort: "none" | "low" | "medium" | "high";
            /** Size */
            size: string;
            /** Websearch */
            webSearch: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Demomode */
            demoMode: boolean;
            /**
             * Service
             * @constant
             */
            service: "canvasrelay-api";
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Version */
            version: string;
        };
        /** ImageEditLoraOption */
        ImageEditLoraOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** ImageEditOptionDefaults */
        ImageEditOptionDefaults: {
            /** Cfg */
            cfg: number;
            /** Sampler */
            sampler: string;
            /** Scheduler */
            scheduler: string;
            /** Steps */
            steps: number;
        };
        /** ImageEditProviderOptionsResponse */
        ImageEditProviderOptionsResponse: {
            defaults: components["schemas"]["ImageEditOptionDefaults"];
            /** Loras */
            loras: components["schemas"]["ImageEditLoraOption"][];
            /** Samplers */
            samplers: string[];
            /** Schedulers */
            schedulers: string[];
        };
        /** ImageEditSettingsResponse */
        ImageEditSettingsResponse: {
            /** Cfg */
            cfg: number;
            fitMode: components["schemas"]["EditFitMode"];
            /** Groundingresolution */
            groundingResolution: number;
            /** Loras */
            loras: components["schemas"]["LoraSelectionResponse"][];
            /** Referenceinfluence */
            referenceInfluence: number;
            /** Sampler */
            sampler: string;
            /** Scheduler */
            scheduler: string;
            /** Steps */
            steps: number;
        };
        /** ImageGenerationOptionDefaults */
        ImageGenerationOptionDefaults: {
            /** Cfg */
            cfg: number;
            /** Sampler */
            sampler: string;
            /** Scheduler */
            scheduler: string;
            /** Shift */
            shift: number;
            /** Steps */
            steps: number;
        };
        /** ImageGenerationProviderOptionsResponse */
        ImageGenerationProviderOptionsResponse: {
            defaults: components["schemas"]["ImageGenerationOptionDefaults"];
            /** Loras */
            loras: components["schemas"]["ImageEditLoraOption"][];
            /** Samplers */
            samplers: string[];
            /** Schedulers */
            schedulers: string[];
        };
        /** ImageGenerationSettingsInput */
        ImageGenerationSettingsInput: {
            /**
             * Cfg
             * @default 1
             */
            cfg: number;
            /** Loras */
            loras?: components["schemas"]["LoraSelectionInput"][];
            /**
             * Sampler
             * @default euler
             */
            sampler: string;
            /**
             * Scheduler
             * @default beta
             */
            scheduler: string;
            /**
             * Shift
             * @default 5
             */
            shift: number;
            /**
             * Steps
             * @default 8
             */
            steps: number;
        };
        /** ImageGenerationSettingsResponse */
        ImageGenerationSettingsResponse: {
            /** Cfg */
            cfg: number;
            /** Loras */
            loras: components["schemas"]["LoraSelectionResponse"][];
            /** Sampler */
            sampler: string;
            /** Scheduler */
            scheduler: string;
            /** Shift */
            shift: number;
            /** Steps */
            steps: number;
        };
        /** ImageJobBatchDelete */
        ImageJobBatchDelete: {
            /** Ids */
            ids: string[];
        };
        /** ImageJobBatchDeleteResponse */
        ImageJobBatchDeleteResponse: {
            /** Deletedids */
            deletedIds: string[];
        };
        /** ImageJobCreate */
        ImageJobCreate: {
            aspectRatio: components["schemas"]["AspectRatio"];
            generation?: components["schemas"]["ImageGenerationSettingsInput"] | null;
            /** Prompt */
            prompt: string;
            /** Seed */
            seed?: number | null;
            style: components["schemas"]["ImageStyle"];
        };
        /** ImageJobError */
        ImageJobError: {
            /** Action */
            action: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ImageJobListResponse */
        ImageJobListResponse: {
            /** Items */
            items: components["schemas"]["ImageJobResponse"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** @enum {string} */
        ImageJobOperation: "generate" | "edit";
        /** ImageJobResponse */
        ImageJobResponse: {
            /** Assets */
            assets?: components["schemas"]["ImageJobResult"][];
            /** Completedat */
            completedAt: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Currentstep */
            currentStep?: number | null;
            error: components["schemas"]["ImageJobError"] | null;
            /** Estimatedremainingseconds */
            estimatedRemainingSeconds?: number | null;
            /** Id */
            id: string;
            phase: components["schemas"]["ImageProgressPhase"];
            /** Progress */
            progress: number | null;
            progressSource: components["schemas"]["ImageProgressSource"];
            /** Prompt */
            prompt: string;
            result: components["schemas"]["ImageJobResult"] | null;
            settings: components["schemas"]["ImageJobSettings"];
            /** Stalled */
            stalled: boolean;
            /** Startedat */
            startedAt: string | null;
            status: components["schemas"]["ImageJobStatus"];
            /** Tags */
            tags?: string[];
            /** Totalsteps */
            totalSteps?: number | null;
        };
        /** ImageJobResult */
        ImageJobResult: {
            /**
             * Available
             * @default true
             */
            available: boolean;
            /** Height */
            height: number;
            mimeType: components["schemas"]["ImageMimeType"];
            /** Sha256 */
            sha256?: string | null;
            /** Sizebytes */
            sizeBytes?: number | null;
            /** Thumbnailurl */
            thumbnailUrl: string;
            /** Url */
            url: string;
            /** Width */
            width: number;
        };
        /** ImageJobSettings */
        ImageJobSettings: {
            aspectRatio: components["schemas"]["AspectRatio"];
            edit?: components["schemas"]["ImageEditSettingsResponse"] | null;
            generation?: components["schemas"]["ImageGenerationSettingsResponse"] | null;
            gpt?: components["schemas"]["GPTImageSettingsResponse"] | null;
            /** Hasfacereference */
            hasFaceReference: boolean;
            operation: components["schemas"]["ImageJobOperation"];
            provider: components["schemas"]["ImageProviderName"];
            /** Seed */
            seed: number;
            /** Sourcejobid */
            sourceJobId?: string | null;
            style: components["schemas"]["ImageStyle"];
        };
        /** @enum {string} */
        ImageJobStatus: "queued" | "running" | "completed" | "failed" | "canceled";
        /** ImageJobTagListResponse */
        ImageJobTagListResponse: {
            /** Tags */
            tags: string[];
        };
        /** ImageJobTagsUpdate */
        ImageJobTagsUpdate: {
            /** Tags */
            tags?: string[];
        };
        /** @enum {string} */
        ImageMimeType: "image/svg+xml" | "image/png" | "image/jpeg" | "image/webp";
        /** @enum {string} */
        ImageProgressPhase: "queued" | "uploading" | "preparing" | "generating" | "sampling" | "saving" | "completed" | "failed" | "canceled";
        /** @enum {string} */
        ImageProgressSource: "provider" | "inferred" | "unknown";
        /** @enum {string} */
        ImageProviderName: "demo" | "comfyui" | "openai_oauth";
        /** ImageProviderResponse */
        ImageProviderResponse: {
            /** Label */
            label: string;
            /** Message */
            message: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "demo" | "live";
            provider: components["schemas"]["ImageProviderName"];
            /** Ready */
            ready: boolean;
        };
        /** @enum {string} */
        ImageStyle: "editorial" | "product" | "concept";
        /** LoraSelectionInput */
        LoraSelectionInput: {
            /** Clipweight */
            clipWeight: number;
            /** Id */
            id: string;
            /** Modelweight */
            modelWeight: number;
        };
        /** LoraSelectionResponse */
        LoraSelectionResponse: {
            /** Clipweight */
            clipWeight: number;
            /** Id */
            id: string;
            /** Modelweight */
            modelWeight: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_connection_status_api_v1_connections_codex_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodexConnectionResponse"];
                };
            };
        };
    };
    disconnect_connection_api_v1_connections_codex_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodexConnectionResponse"];
                };
            };
        };
    };
    check_connection_api_v1_connections_codex_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodexConnectionResponse"];
                };
            };
        };
    };
    import_connection_api_v1_connections_codex_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodexConnectionResponse"];
                };
            };
        };
    };
    restart_connection_api_v1_connections_codex_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CodexConnectionResponse"];
                };
            };
        };
    };
    create_gpt_image_job_api_v1_gpt_image_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_gpt_image_job_api_v1_gpt_image_jobs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_image_edit_job_api_v1_image_edit_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_image_edit_job_api_v1_image_edit_jobs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_image_jobs_api_v1_image_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                status?: components["schemas"]["ImageJobStatus"] | null;
                operation?: components["schemas"]["ImageJobOperation"] | null;
                search?: string | null;
                tag?: string | null;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_image_job_api_v1_image_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_job_assets_api_v1_image_jobs_assets_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageJobBatchDelete"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobBatchDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_image_job_tags_api_v1_image_jobs_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobTagListResponse"];
                };
            };
        };
    };
    get_image_job_api_v1_image_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_image_job_api_v1_image_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_job_asset_api_v1_image_jobs__job_id__asset_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_job_asset_result_api_v1_image_jobs__job_id__assets__ordinal__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                ordinal: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_job_asset_thumbnail_api_v1_image_jobs__job_id__assets__ordinal__thumbnail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                ordinal: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_image_job_api_v1_image_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_job_input_api_v1_image_jobs__job_id__inputs__role__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_job_input_ordinal_api_v1_image_jobs__job_id__inputs__role___ordinal__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                role: string;
                ordinal: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_job_result_api_v1_image_jobs__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_image_job_api_v1_image_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_image_job_tags_api_v1_image_jobs__job_id__tags_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageJobTagsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_job_thumbnail_api_v1_image_jobs__job_id__thumbnail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_provider_api_v1_providers_image_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageProviderResponse"];
                };
            };
        };
    };
    get_image_edit_provider_api_v1_providers_image_edit_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageProviderResponse"];
                };
            };
        };
    };
    get_image_edit_options_api_v1_providers_image_edit_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageEditProviderOptionsResponse"];
                };
            };
        };
    };
    get_image_generation_options_api_v1_providers_image_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageGenerationProviderOptionsResponse"];
                };
            };
        };
    };
}
