/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Image Job */
        post: operations["create_image_job_api_v1_image_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Job */
        get: operations["get_image_job_api_v1_image_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Image Job */
        delete: operations["cancel_image_job_api_v1_image_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/image-jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Job Result */
        get: operations["get_image_job_result_api_v1_image_jobs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/providers/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Image Provider */
        get: operations["get_image_provider_api_v1_providers_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AspectRatio: "1:1" | "4:3" | "3:4" | "16:9";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Demomode */
            demoMode: boolean;
            /**
             * Service
             * @constant
             */
            service: "canvasrelay-api";
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Version */
            version: string;
        };
        /** ImageJobCreate */
        ImageJobCreate: {
            aspectRatio: components["schemas"]["AspectRatio"];
            /** Prompt */
            prompt: string;
            /** Seed */
            seed?: number | null;
            style: components["schemas"]["ImageStyle"];
        };
        /** ImageJobError */
        ImageJobError: {
            /** Action */
            action: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ImageJobResponse */
        ImageJobResponse: {
            /** Completedat */
            completedAt: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            error: components["schemas"]["ImageJobError"] | null;
            /** Id */
            id: string;
            /** Progress */
            progress: number | null;
            /** Prompt */
            prompt: string;
            result: components["schemas"]["ImageJobResult"] | null;
            settings: components["schemas"]["ImageJobSettings"];
            /** Startedat */
            startedAt: string | null;
            status: components["schemas"]["ImageJobStatus"];
        };
        /** ImageJobResult */
        ImageJobResult: {
            /** Height */
            height: number;
            mimeType: components["schemas"]["ImageMimeType"];
            /** Url */
            url: string;
            /** Width */
            width: number;
        };
        /** ImageJobSettings */
        ImageJobSettings: {
            aspectRatio: components["schemas"]["AspectRatio"];
            provider: components["schemas"]["ImageProviderName"];
            /** Seed */
            seed: number;
            style: components["schemas"]["ImageStyle"];
        };
        /** @enum {string} */
        ImageJobStatus: "queued" | "running" | "completed" | "failed" | "canceled";
        /** @enum {string} */
        ImageMimeType: "image/svg+xml" | "image/png" | "image/jpeg" | "image/webp";
        /** @enum {string} */
        ImageProviderName: "demo" | "comfyui";
        /** ImageProviderResponse */
        ImageProviderResponse: {
            /** Label */
            label: string;
            /** Message */
            message: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "demo" | "live";
            provider: components["schemas"]["ImageProviderName"];
            /** Ready */
            ready: boolean;
        };
        /** @enum {string} */
        ImageStyle: "editorial" | "product" | "concept";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_image_job_api_v1_image_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageJobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_job_api_v1_image_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_image_job_api_v1_image_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_job_result_api_v1_image_jobs__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_provider_api_v1_providers_image_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageProviderResponse"];
                };
            };
        };
    };
}
